/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundImg: typeof import('./components/BackgroundImg.vue')['default']
    Dust2: typeof import('./components/Dust2.vue')['default']
    RainEffect: typeof import('./components/RainEffect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    Unknow: typeof import('./components/Unknow.vue')['default']
  }
}
